name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hi there fellas
      - name: Print goodbye
        run: echo "it's been a pleasure to meet you"
